name: Get latest dynamic part /net-binnen.json URL

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 */4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Executable script
      run: chmod +x ./get-dynamic-part-net-binnen-url.js
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps chromium
    - name: Get dynamic part
      run: node ./get-dynamic-part-net-binnen-url.js
    - name: Commit and push if new news events
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Dynamic part /net-binnen.json URL updated: ${timestamp}" || exit 0
        git push