name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '0 5,17 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Executable fetch recent news events script
      run: chmod +x ./fetch-recent-news-events.sh
    - name: Fetch recent news events
      run: ./fetch-recent-news-events.sh
    - name: Commit and push if new news events
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push